
language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install -y default-jdk ant
  - pip install pubrunner

install:

  - sh install_gnormplus_java.sh
  - sh install_tmchem_model1_java.sh
  - sh install_tmvar.sh 
script:
  - pubrunner --defaultsettings --test .


